import { LayoutBase } from '@/layouts/LayoutBase/LayoutBaset';
import '@/styles/globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body className={inter.className}>
      <LayoutBase>{children}</LayoutBase>
    </body>
  </html>
);

export default RootLayout;
